# References
# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
# https://gohugo.io/hosting-and-deployment/hosting-on-netlify/
# https://www.josephearl.co.uk/post/static-sites-netlify-security/

[build]
publish = "public"
command = "hugo --gc --minify --buildDrafts"

[context.production.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_BASEURL = "https://computersecuritytips.info"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.2"

[context.branch-deploy]
command = "hugo --gc --minify --buildDrafts -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    # Block site from being framed with X-Frame-Options and CSP
    Content-Security-Policy: frame-ancestors 'none'
    X-Frame-Options: DENY

    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options: nosniff

    X-XSS-Protection = "1; mode=block"
